server.port=8082

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:root}
spring.rabbitmq.password=${RABBITMQ_PASS:root}

rabbitmq.exchange=messages.exchange
rabbitmq.queue=messages.queue
rabbitmq.routing-key=messages.key

spring.rabbitmq.listener.simple.missing-queues-fatal=false
